### ISSUE TITLE
emscripten+SDL2 tutorial inaccessible

### ISSUE THREAD

**Issue by powertomato** [lyceum-allotments/lyceum-allotments.github.io#1]
Hi,
parts of your emscripten+SDL2 tutorial seem to be inaccessible

http://lyceum-allotments.github.io/2016/06/emscripten-and-sdl2-tutorial-part-3-hello-world/
http://lyceum-allotments.github.io/2016/06/emscripten-and-sdl2-tutorial-part-4-look-owl/

however it works if you put "index.html" at the end, may be a server conf. issue?

Great tutorial by the way. It helped me a lot.

**Comment by lyceum-allotments** [comment]
Hi,

Thanks for pointing this out, I've just changed some settings on the site and am waiting for it to rebuild, it should be back up within the hour, sorry for any inconvenience.

I'm glad you find it helpful!

**Comment by lyceum-allotments** [comment]
Okay, everything should be accessible now,

Thanks again!
